// Dependency-free PDF generator for the notarial Purchase Contract.
//
// Builds a minimal but valid single-page A4 PDF (Helvetica / Helvetica-Bold,
// WinAnsi encoding) entirely client-side — no external library required, which
// keeps it working even without node_modules installed. The whole document is
// assembled as an ASCII string (accented characters are emitted as octal
// escapes) so byte offsets used in the xref table match string indices exactly.

export interface PurchaseContractData {
  contractNumber: string;
  date: string;
  notary: string;
  buyerName: string;
  buyerId: string;
  sellerName: string;
  sellerId: string;
  propertyDescription: string;
  propertyAddress: string;
  price: string;
}

// Map common "smart" Unicode punctuation (above U+00FF) to their Windows-1252 /
// WinAnsiEncoding byte values so the standard Helvetica font can render them.
const WINANSI: Record<number, number> = {
  0x20ac: 0x80, // euro
  0x2013: 0x96, // en dash
  0x2014: 0x97, // em dash
  0x2018: 0x91, // left single quote
  0x2019: 0x92, // right single quote / apostrophe
  0x201c: 0x93, // left double quote
  0x201d: 0x94, // right double quote
  0x2022: 0x95, // bullet
  0x2026: 0x85, // ellipsis
  0x2122: 0x99, // trademark
};

// Escape a string for inclusion inside a PDF text-showing operator: parentheses
// and backslashes are escaped, and any non-ASCII character is written as a
// three-digit octal escape of its WinAnsi byte so the surrounding document stays
// pure ASCII. Accented Latin-1 characters (<= U+00FF) map 1:1 to their byte.
const escapePdfText = (input: string): string => {
  let out = "";
  for (const ch of input) {
    const code = ch.codePointAt(0) ?? 0;
    if (ch === "(") out += "\\(";
    else if (ch === ")") out += "\\)";
    else if (ch === "\\") out += "\\\\";
    else if (code < 32 || code > 126) {
      const byte = code <= 255 ? code : WINANSI[code];
      out += byte !== undefined ? "\\" + byte.toString(8).padStart(3, "0") : "?";
    } else {
      out += ch;
    }
  }
  return out;
};

interface Line {
  text: string;
  size: number;
  bold?: boolean;
  gapAfter?: number; // extra points of vertical space after this line
}

const A4_WIDTH = 595.28;
const A4_HEIGHT = 841.89;
const MARGIN_X = 60;
const TOP_Y = 790;

const buildContentStream = (data: PurchaseContractData): string => {
  const lines: (Line | null)[] = [
    { text: "CENTRE TECNOLOGIC DEL NOTARIAT", size: 9, bold: true, gapAfter: 2 },
    { text: "Portal Notarial - Escriptura de Compravenda", size: 9, gapAfter: 14 },
    { text: "PURCHASE CONTRACT", size: 22, bold: true, gapAfter: 4 },
    { text: "Notarial deed of sale and purchase", size: 11, gapAfter: 18 },

    { text: "Contract number:  " + data.contractNumber, size: 11, bold: true },
    { text: "Date of execution:  " + data.date, size: 11 },
    { text: "Officiating notary:  " + data.notary, size: 11, gapAfter: 18 },

    { text: "1. PARTIES", size: 13, bold: true, gapAfter: 8 },
    { text: "Purchaser (Buyer):", size: 11, bold: true },
    { text: data.buyerName, size: 11 },
    { text: "Identification: " + data.buyerId, size: 10, gapAfter: 10 },
    { text: "Vendor (Seller):", size: 11, bold: true },
    { text: data.sellerName, size: 11 },
    { text: "Identification: " + data.sellerId, size: 10, gapAfter: 18 },

    { text: "2. OBJECT OF THE CONTRACT", size: 13, bold: true, gapAfter: 8 },
    { text: data.propertyDescription, size: 11 },
    { text: data.propertyAddress, size: 11, gapAfter: 10 },
    { text: "Total purchase price:  " + data.price, size: 12, bold: true, gapAfter: 18 },

    { text: "3. DECLARATIONS", size: 13, bold: true, gapAfter: 8 },
    {
      text: "The parties, having appeared before the notary, mutually agree to the",
      size: 11,
    },
    {
      text: "sale and purchase of the object described above for the stated price.",
      size: 11,
    },
    {
      text: "The seller declares the object to be free of liens and encumbrances,",
      size: 11,
    },
    {
      text: "and the buyer accepts it in its current legal and physical condition.",
      size: 11,
    },
    {
      text: "Identity of both parties was verified through their digital wallets.",
      size: 11,
      gapAfter: 30,
    },

    { text: "Signed and sealed before the notary,", size: 11, gapAfter: 40 },
    { text: "_______________________________", size: 11, gapAfter: 2 },
    { text: data.notary, size: 10 },
    { text: "Notary - Centre Tecnologic del Notariat", size: 9, gapAfter: 24 },
    {
      text: "This document was generated by the CTN portal as a demonstration and",
      size: 8,
    },
    {
      text: "does not constitute a legally binding notarial instrument.",
      size: 8,
    },
  ];

  const ops: string[] = [];
  let y = TOP_Y;
  for (const line of lines) {
    if (!line) {
      y -= 12;
      continue;
    }
    const font = line.bold ? "/F2" : "/F1";
    ops.push(
      `BT ${font} ${line.size} Tf 1 0 0 1 ${MARGIN_X} ${y.toFixed(2)} Tm (${escapePdfText(
        line.text,
      )}) Tj ET`,
    );
    y -= line.size + 6 + (line.gapAfter ?? 0);
  }

  // A thin horizontal rule under the header.
  const ruleY = TOP_Y - 44;
  ops.push(
    `0.55 0.55 0.55 RG 1 w ${MARGIN_X} ${ruleY.toFixed(2)} m ${(
      A4_WIDTH - MARGIN_X
    ).toFixed(2)} ${ruleY.toFixed(2)} l S`,
  );

  return ops.join("\n");
};

export const generatePurchaseContractPdf = (data: PurchaseContractData): Blob => {
  const content = buildContentStream(data);

  const objects: string[] = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${A4_WIDTH.toFixed(2)} ${A4_HEIGHT.toFixed(
      2,
    )}] /Resources << /Font << /F1 4 0 R /F2 5 0 R >> >> /Contents 6 0 R >>`,
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>",
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>",
    `<< /Length ${content.length} >>\nstream\n${content}\nendstream`,
  ];

  let pdf = "%PDF-1.4\n";
  const offsets: number[] = [];
  objects.forEach((body, i) => {
    offsets.push(pdf.length);
    pdf += `${i + 1} 0 obj\n${body}\nendobj\n`;
  });

  const xrefStart = pdf.length;
  const count = objects.length + 1;
  pdf += `xref\n0 ${count}\n`;
  pdf += "0000000000 65535 f \n";
  for (const off of offsets) {
    pdf += off.toString().padStart(10, "0") + " 00000 n \n";
  }
  pdf += `trailer\n<< /Size ${count} /Root 1 0 R >>\nstartxref\n${xrefStart}\n%%EOF`;

  // The document is pure ASCII, so Latin-1/UTF-8 bytes are identical and the
  // xref offsets computed from string indices are byte-accurate.
  const bytes = new Uint8Array(pdf.length);
  for (let i = 0; i < pdf.length; i++) bytes[i] = pdf.charCodeAt(i) & 0xff;
  return new Blob([bytes], { type: "application/pdf" });
};

export const downloadPurchaseContract = (data: PurchaseContractData): void => {
  const blob = generatePurchaseContractPdf(data);
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `Purchase-Contract-${data.contractNumber}.pdf`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
};
